# Generated by Agent B — Lint & Type Scripts
.PHONY: lint test format typecheck format-check

lint:
	ruff check src/ tests/

format:
	ruff format src/ tests/

format-check:
	ruff format --check src/ tests/

typecheck:
	pyright src/

test:
	pytest -q
